// --- Directions
// Write a function that accepts a positive number N.
// The function should console log a step shape
// with N levels using the # character.  Make sure the
// step has spaces on the right hand side!
// --- Examples
//   steps(2)
//       '# '
//       '##'
//   steps(3)
//       '#  '
//       '## '
//       '###'
//   steps(4)
//       '#   '
//       '##  '
//       '### '
//       '####'

/*
    1. We can use a while loop and set that equal to n
        a. each iteration will console log astring whos length is equal to n as well
        b. tbat will be generated by a asecond loop
*/

const steps = n => {
    let stepCount = 1
    let logString = ""
    while (stepCount <= n) {
        console.log(`Step Count: ${stepCount} n: ${n}`)
        stepCount++;


    }
}

steps(4)

module.exports = steps;
